### ISSUE TITLE
Cannot make the bootloader for the Icebreaker bitsy :(

### ISSUE THREAD

**Issue by tuabu** [no2fpga/no2bootloader#10]
turbo@core:~/fpga/bootloader/no2bootloader/gateware/ice40-stub$ make BOARD=bitsy-v1 bootloader
Makefile:33: ../build/project-rules.mk: No such file or directory
make: *** No rule to make target '../build/project-rules.mk'.  Stop.
Please send help .-.
I think it has to do with the riscv toolchain but i don't know much about this stuff.

**Comment by smunaut** [comment]
You need to make a recursive checkout of the repo or to manually init the submodules with :+1: 
```
git submodules init
git submodules update
```

**Comment by tuabu** [comment]
Thank u for your help!!!!
@ least i get another error message:
turbo@core:~/fpga/bootloader/no2bootloader/gateware/ice40-stub$ make BOARD=bitsy-v1 bootloader
make: yosys-config: Command not found
if test "" = "1"; then \
	make clean; \
	make -C /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40 clean; \
	make -C /home/turbo/fpga/bootloader/no2bootloader/firmware clean; \
	mkdir -p /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp; \
fi
cd /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp && \
	yosys -s /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp/ice40-stub.ys \
		 -l /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp/ice40-stub.synth.rpt
/bin/sh: 2: yosys: not found
make: *** [../build/project-rules.mk:85: /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp/ice40-stub.json] Error 127

but i should have yosys-toolchain in the path
turbo@core:~$ echo $PATH
fpga/fpga-toolchain/bin:/home/turbo/.local/bin:....

**Comment by tuabu** [comment]
I have updated yosys fpga-toolchain to the path as well as the riscv-toolchain and now when i do 
make BOARD=bitsy-v1 PRE-CLEAN=1 CROSS=riscv-none-embed bootloader

i get this @ the end:
Info: Program finished normally.
icepack -s /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp/ice40-stub.asc /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp/ice40-stub.bin
./sw/mkmultiboot.py /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp/bootloader.bin /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40-stub/build-tmp/ice40-stub.bin /home/turbo/fpga/bootloader/no2bootloader/gateware/ice40/build-tmp/no2bootloader-ice40.bin:/home/turbo/fpga/bootloader/no2bootloader/firmware/no2bootloader-bitsy-v1.bin
 I think this is alright and I can now program via iceprog the bootloader.bin in build-temp/ to the flash memory of the fpga, right?
Thank you for your help smunaut and great repo!!!!!

**Comment by smunaut** [comment]
Yeah, that should be good to flash.

Didn't your board come with a bootloader pre-loaded ?

**Comment by tuabu** [comment]
I can't buy the bitsy anywhere the campaign has ended and so it is out of stock as I know :(
As a result I am building the bitsy by myself and hope everything will be alright. :)
